// <auto-generated />
using System;
using AiSync.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AiSync.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260519071449_SeedEmployees")]
    partial class SeedEmployees
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AiSync.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1990, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Ana García"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1985, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Carlos López"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1993, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "María Rodríguez"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(1988, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "Jorge Martínez"
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(1995, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Laura Sánchez"
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateTime(1982, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Pedro Hernández"
                        },
                        new
                        {
                            Id = 7,
                            DateOfBirth = new DateTime(1997, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Sofía Torres"
                        },
                        new
                        {
                            Id = 8,
                            DateOfBirth = new DateTime(1991, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "Diego Ramírez"
                        },
                        new
                        {
                            Id = 9,
                            DateOfBirth = new DateTime(1994, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Valentina Cruz"
                        },
                        new
                        {
                            Id = 10,
                            DateOfBirth = new DateTime(1987, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Andrés Flores"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
